

export const sample_foods: any[] = [

  {
    id: "1",
    title: "Psychology of Money",
    price: 10,
    author: "Morgan Housel ",
    subject:
      " In the psychology of money, the author shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life?s most important matters.",
    publish_date: "1-09-2020",
    imageUrl: "assets/psychology_of_money.jpg",
    tags: ["psychology", "money"],
  },
  {
    id: "2",
    title: "Commit To Yourself",

    price: 10,
    author: "Nancy Katyal",
    subject:
      " The various self-reflective exercises in the book help you to accept yourself, love yourself and improve yourself, not just your self-image.",
    publish_date: "30-11-2022",
    imageUrl: "assets/commit_to_yourself.jpg",
    tags: ["self love"],
  },
  {
    id: "3",
    title: "The Happiness Hypothesis",

    price: 10,
    author: "Jonathan Haidt",
    subject:
      "The Happiness Hypothesis as an accessible vessel for his research into moral foundations theory.",
    publish_date: "1-09-2020",
    imageUrl: "assets/the_happiness_hypothesis.jpg",
    tags: ["psychology"
    ],
  },
  {
    id: "4",
    title: "Influence : The Psychology of Persuasion",

    price: 10,
    author: "PhD Robert B. Cialdini",
    subject:
      "Each of the seven principles has a dedicated chapter to describe how it functions, where it’s most applicable, and — most importantly — how you apply it in your own life. ",
    publish_date: "1-09-2020",
    imageUrl: "assets/influence.jpg",
    tags: [
    "Business"],
  },
  {
    id: "5",
    title: " Mistakes Were Made (but Not by Me)",

    price: 10,
    author: "Carol Tavri",
    subject:
      "The next entry on this list might clarify some of these seemingly illogical decisions:  in Mistakes Were Made, Carol Tavris and Elliot Aronsondiscuss the systematic mental patterns which feed into development and radicalization of human beliefs.",
    publish_date: "1-09-2020",
    imageUrl: "assets/psychology_of_money.jpg",
    tags: ["Fantasy"],
  },
  {
    id: "6",
    title: "Broken Bonds",

    price: 10,
    author: "J Bree",
    subject:
      " After the death of my mother and her Bonded, I was relieved to find my own Bonds. I was sure everything would be okay if I had them. It wasn’t. The fate of our people is in my hands and I know we’re better off if I’m alone. After five years on the run, I’m caught and dragged back to face the men I ran away from. I thought I was doing the right thing. Now, I’m not so sure. North, Nox, Gryphon, Atlas, and Gabe may never forgive me but one thing is for sure. I won’t ever forgive myself.    ",
    publish_date: "28-6-2021",
    imageUrl: "assets/Broken_Bonds.jpg",
    tags: ["bonds"],
  },
  {
    id: "7",
    title: " Deceived by the Gargoyles",

    price: 15,
    author: " Lillian Lark",
    subject:
      " My family has always found me lacking. From the way I dress, how I look, to the type of magic I have. My family name is full of pomp and prestige, and I want nothing to do with it I am a witch that knows how to set a goal and I have one in mind.",
    publish_date: "31-01-2022",
    imageUrl: "assets/Lillian_Lark.jpg",
    tags: ["Fantasy"],
  },
  {
    id: "8",
    title: "The Never King ",
    price: 17,
    author: " Nikki St. Crowe",
    subject:
      " The Never King is a reimagining of Peter and Wendy. Characters have been aged up for this darker, grittier version. If you like your enemies to lovers romance with hot, ruthless, morally gray love interests, you’ll enjoy The Never King and the Lost Boys. You can expect hate kissing, fighting, bickering, and ‘touch her and I’ll unalive you’ vibes. Book one ends on a cliff. ",
    publish_date: "24-2-2022",
    imageUrl: "assets/the_never_king.jpg",
    tags: ["Fantasy"],
  },
  {
    id: "9",
    title: "Stalked by the Kraken:",
    price: 11,
    author: " Lillian Lark ",
    subject:
      "Stalked by the Kraken is a monster romance that features tentacles. This book is a standalone and takes place in the same world as, and prior to the events of, Three of Hearts with some character crossover.",
    publish_date: "29-06-2021",
    imageUrl: "assets/stalked_by_the_kraken.jpg",
    tags: ["Fantasy",],
  },
  {
    id: "10",
    title: "We Were Liars ",
    price: 10,
    author: "  E. Lockhart ",
    subject:
      "We Were Liars, is clever, alluring, and wildly addictive. Each summer the wealthy, seemingly perfect, members of the Sinclair family gather on their private island. We Were Liars is the story of those annual reunions; in particular what happened during a summer that protagonist Cadence is unable to remember. Prejudice, greed, and shifting patriarchal favoritism among the three adult sisters contrasts with the camaraderie and worldview of the teenage cousins and their dear friend Gat. ",
    publish_date: "",
    imageUrl: "assets/we_were_liars.jpg",
    tags: [
        "Contemporary",
        "Fiction"],
  },
  {
    id: "11",
    title: "How to Be Bad Kindle Edition",
    price: 19,
    author: "  Lauren Myracle ",
    subject:
      "Best friends, Jess and Vicks, aren't clicking like they use to, so Jess has a plan that will bring her and Vicks close again - a road trip to see Vicks's boyfriend, Brady, who is at University. There's only one issue, they don't have enough money to fund the trip. Enter Mel, the new girl. Mel volunteers to help them fund the trip as long as they take her along with them, much to Jess's dismay. ",
    publish_date: "21-04-2009",
    imageUrl: "assets/how_to_Be_Bad.jpg",
    tags: ["Contemporary"],
  },
  {
    id: "12",
    title: "If the Shoe Fits",
    price: 10,
    author: "  Sarah Mlynowski  ",
    subject:
      " A series puts a fresh spin on the Cinderella story!Tonight the mirror swept us into Cinderella's fairy tale. Now, we are NOT messing this story up. No way. Cinderella is going to marry her prince just like she's supposed to. Uh-oh. Cinderella broke her foot and there's massive swelling. The glass slipper won't fit, the prince won't know she's the one for him, and they won't live happily ever after.",
    publish_date: "01-01-2013",
    imageUrl: "assets/shoe_fits.jpg",
    tags: [ "Contemporary"],
  },
  {
    id: "13",
    title: "Where the Sky Begins",
    price: 12,
    author: "  Rhys Bowen ",
    subject:
      " A woman’s future is determined by fate and choice in a gripping WWII novel about danger, triumph, and second chances by the New York Times bestselling author of The Venice Sketchbook and The Tuscan Child. ",
    publish_date: "2-08-2022",
    imageUrl: "assets/where_the_sky_begins.jpg",
    tags: ["Fiction"],
  },
  {
    id: "14",
    title: "What Divides Us",
    price: 14,
    author: " Jean Grainger ",
    subject: " 29-07-2022 ",
    publish_date:
      "On the face of it, life is idyllic for Eli and Lena Kogan. Living in their beautiful house in the Irish countryside, their children are growing up happy and safe surrounded by a loving community. ",
    imageUrl: "assets/what_divides_us.jpg",
    tags: ["Fiction"],
  },
  {
    id: "15",
    title: "Light to the Hills",
    price: 15,
    author: " Bonnie Blaylock ",
    subject:
      " A beautiful story about life in the Appalachian hills in the 1930s. Men were in the coal mines, there was no education for girls, life was beyond poor. But for the MacInteer Family their faith and family pulled them through, and they persevered.",
    publish_date: "02-12-2022",
    imageUrl: "assets/light_to_hills.jpg",
    tags: ["Fiction"],
  },
  {
    id: "16",
    title: " 2 States ( The Story Of My Marriage)",
    price: 15,
    author: " Chetan Bhagat  ",
    subject:
      "Love marriages around the world are simple: Boy loves girl. Girl loves boy. They get married. In India, there are a few more steps: Boy loves Girl. Girl loves Boy. Girl's family has to love boy. Boy's family has to love girl. Girl's Family has to love Boy's Family. Boy's family has to love girl's family. Girl and Boy still love each other.",
    publish_date: "10-07-2021",
    imageUrl: "assets/2_states.jpg",
    tags: ["Contemporary"],
  },
  {
    id: "17",
    title: "  Halfgirlfriend  ",
    price: 8,
    author: " Chetan Bhagat",
    subject:
      " Half Girlfriend is an Indian English coming of age, young adult romance novel by Indian author Chetan Bhagat.[1] The novel, set in rural Bihar, New Delhi, Patna, and New York, is the story of a Bihari boy on a quest of winning over the girl he loves. ",
    publish_date: "13-08-2014",
    imageUrl: "assets/halfgirlfriend.jpg",
    tags: ["Contemporary"],
  },
  {
    id: "18",
    title: " The Old Curiosity Shop ",
    price: 19,
    author: " Charles Dickens ",
    subject:
      ' With The Old Curiosity Shop we have exactly that experience - in abundance. Plus in the final chapter we have, as always, a satisfying explanation of what has happened to all the main characters. Even the cantankerous and self-willed horse "Whiskers", whose antics more than once released the tension from a particularly harrowing part of the story, is given his own summing-up, his own "happy ending" in the final chapter.  ',
    publish_date: "01-01-1840",
    imageUrl: "assets/the_old_curiosity_shop.jpg",
    tags: ["Fiction"],
  },
  {
    id: "19",
    title: "Open Secrets",
    price: 13,
    author: "Alice Munro ",
    subject:
      " Alice Munro’s Open Secrets is so liberating and exciting for any new story writer to feel her open textures, her bold reach, her plainness, with no showing off, no special effects. She reminds us that there’s no formula for a story, it can be as loosely woven as you like, as long as the inner logic works organically. Easier said of course, much easier said, than done. ",
    publish_date: "  01-12-2005  ",
    imageUrl: "assets/open.jpg",
    tags: [" Politics"],
  },
  {
    id: "20",
    title: "  Our Story Begins ",
    price: 16,
    author: " Tobias Wolff ",
    subject:
      " Tobias Wolff’s Our Story Begins is much more than a vast manual of examples of how to build great characters, unforgettable situations, and powerful dialogues. It shows how great stories are always born of small details and grow thanks to a power of invocation that is reinforced word by word, as a vital spell, which can only be built by walking hand in hand with the reader. ",
    publish_date: " 07-04-2009",
    imageUrl: "assets/our_story_begins.jpg",
    tags: ["Fiction"],
  },
  {
    id: "21",
    title: "A Good Man Is Hard to Find",
    price: 4,
    author: " Flannery O’Connor ",
    subject:
      " Every young writer should read Flannery O’Connor’s A Good Man Is Hard to Find at least three or four times. If you’ve ever thought creativity was opposed to clarity, or that funny stories aren’t serious, or that stories about abnormal people are about abnormal people, or that the road to the realistic was through realism—O’Connor is here to disabuse you, with pleasure.  ",
    publish_date: "08-09-2003",
    imageUrl: "assets/goodman_hard_to_find.jpg",
    tags: [" Fiction"],
  },
  {
    id: "22",
    title: "Airships",
    price: 9,
    author: " Barry Hannah ",
    subject:
      " Hannah’s work was an attack on hungry time itself—his words—and the campaign was successful.  His stories are alive.  I recommend them to readers and writers for the surprise and uplift of his prose. His sentences abound with syntactical twists, archaic words, bardlike phrases, Biblical notes.",
    publish_date: "01-01-2009",
    imageUrl: "assets/airships.jpg",
    tags: ["Literature"],
  },
  {
    id: "23",
    title: " Oliver Twist ",
    price: 18,
    author: " Charles Dickens ",
    subject:
      "Oliver Twist is born into a life of poverty and misfortune, raised in a workhouse in the fictional town of Mudfog. The children working there receive very little food; after six months, they draw lots, with the loser asking for another portion of gruel. Oliver is designated, and so he approaches workhouse manager Mr. Bumble and humbly requests another serving. ",
    publish_date: "09-02-1837",
    imageUrl: "assets/oliver_twist.jpg",
    tags: ["Literature"],
  },
  {
    id: "24",
    title: " Geronimo Rex",
    price: 18,
    author: " Barry Hannah ",
    subject:
      "Geronimo Rex, Barry Hannah's brilliant first novel, which was nominated for the National Book Award, is full of the rare verve and flawless turns of phrase that have defined his status as an American master. Roiling with love and torment, lunacy and desire, hilarity and tenderness, Geronimo Rex is the bildungsroman of an unlikely hero.",
    publish_date: "09-02-1837",
    imageUrl: "assets/geronimo_rex.jpg",
    tags: ["Fiction", "Literature"],
  },

]

export const sample_tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'psychology', count: 4 },
  { name: 'self love', count: 2 },
  { name: 'Literature', count: 3 },
  { name: 'Classics', count: 2 },
  { name: 'Fiction', count: 1 },
  { name: 'Fantasy', count: 1 },
  { name: 'Contemporary', count: 1 },
]

export const sample_users: any[] = [
  {
    name:"John Deo",
    email:"john@gmail.com",
    password: "12345",
    adress: "xyz",
    isAdmin: true
  },
  {
    name:"Jane Deo",
    email:"jane@gmail.com",
    password: "12345",
    adress: "zxy",
    isAdmin: true
  },
]


// [

//   {
//     "id": 1,
//     "title": "Psychology of Money",
//     "price": 10,
//     "author": "Morgan Housel ",
//     "subject":" In the psychology of money, the author shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life?s most important matters.",
//     "publish_date": "1-09-2020",
//     "imageUrl": "assets/psychology_of_money.jpg",
//     "tags": ["psychology", "money"],
//   },
//   {
//     "id": 2,
//     "title": "Commit To Yourself",

//     "price": 10,
//     "author": "Nancy Katyal",
//     "subject":" The various self-reflective exercises in the book help you to accept yourself, love yourself and improve yourself, not just your self-image.",
//     "publish_date": "30-11-2022",
//     "imageUrl": "assets/commit_to_yourself.jpg",
//     "tags": ["self love"],
//   },
//   {
//     "id": 3,
//     "title": "The Happiness Hypothesis",
//     "price": 10,
//     "author": "Jonathan Haidt",
//     "subject":"The Happiness Hypothesis as an accessible vessel for his research into moral foundations theory.",
//     "publish_date": "1-09-2020",
//     "imageUrl": "assets/the_happiness_hypothesis.jpg",
//     "tags": ["psychology"
//     ],
//   },
//   {
//     "id": 4,
//     "title": "Influence : The Psychology of Persuasion",

//     "price": 10,
//     "author": "PhD Robert B. Cialdini",
//     "subject":"Each of the seven principles has a dedicated chapter to describe how it functions, where it’s most applicable, and — most importantly — how you apply it in your own life. ",
//     "publish_date": "1-09-2020",
//     "imageUrl": "assets/influence.jpg",
//     "tags": [
//     "Business"],
//   },
//   {
//     "id": 5,
//     "title": " Mistakes Were Made (but Not by Me)",
//     "price": 10,
//     "author": "Carol Tavri",
//     "subject":"The next entry on this list might clarify some of these seemingly illogical decisions:  in Mistakes Were Made, Carol Tavris and Elliot Aronsondiscuss the systematic mental patterns which feed into development and radicalization of human beliefs.",
//     "publish_date": "1-09-2020",
//     "imageUrl": "assets/psychology_of_money.jpg",
//     "tags": ["Fantasy"],
//   },
//   {
//     "id": 6,
//     "title": "Broken Bonds",

//     "price": 10,
//     "author": "J Bree",
//     "subject":" After the death of my mother and her Bonded, I was relieved to find my own Bonds. I was sure everything would be okay if I had them. It wasn’t. The fate of our people is in my hands and I know we’re better off if I’m alone. After five years on the run, I’m caught and dragged back to face the men I ran away from. I thought I was doing the right thing. Now, I’m not so sure. North, Nox, Gryphon, Atlas, and Gabe may never forgive me but one thing is for sure. I won’t ever forgive myself.    ",
//     "publish_date": "28-6-2021",
//     "imageUrl": "assets/Broken_Bonds.jpg",
//     "tags": ["bonds"],
//   },
//   {
//     "id": 7,
//     "title": " Deceived by the Gargoyles",
//     "price": 15,
//     "author": " Lillian Lark",
//     "subject":" My family has always found me lacking. From the way I dress, how I look, to the type of magic I have. My family name is full of pomp and prestige, and I want nothing to do with it I am a witch that knows how to set a goal and I have one in mind.",
//     "publish_date": "31-01-2022",
//     "imageUrl": "assets/Lillian_Lark.jpg",
//     "tags": ["Fantasy"],
//   },
//   {
//     "id": 8,
//     "title": "The Never King ",
//     "price": 17,
//     "author": " Nikki St. Crowe",
//     "subject":" The Never King is a reimagining of Peter and Wendy. Characters have been aged up for this darker, grittier version. If you like your enemies to lovers romance with hot, ruthless, morally gray love interests, you’ll enjoy The Never King and the Lost Boys. You can expect hate kissing, fighting, bickering, and ‘touch her and I’ll unalive you’ vibes. Book one ends on a cliff. ",
//     "publish_date": "24-2-2022",
//     "imageUrl": "assets/the_never_king.jpg",
//     "tags": ["Fantasy"],
//   },
//   {
//     "id": 9,
//     "title": "Stalked by the Kraken:",
//     "price": 11,
//     "author": " Lillian Lark ",
//     "subject":"Stalked by the Kraken is a monster romance that features tentacles. This book is a standalone and takes place in the same world as, and prior to the events of, Three of Hearts with some character crossover.",
//     "publish_date": "29-06-2021",
//     "imageUrl": "assets/stalked_by_the_kraken.jpg",
//     "tags": ["Fantasy",],
//   },
//   {
//     "id": 10,
//     "title": "We Were Liars ",
//     "price": 10,
//     "author": "  E. Lockhart ",
//     "subject":"We Were Liars, is clever, alluring, and wildly addictive. Each summer the wealthy, seemingly perfect, members of the Sinclair family gather on their private island. We Were Liars is the story of those annual reunions; in particular what happened during a summer that protagonist Cadence is unable to remember. Prejudice, greed, and shifting patriarchal favoritism among the three adult sisters contrasts with the camaraderie and worldview of the teenage cousins and their dear friend Gat. ",
//     "publish_date": "",
//     "imageUrl": "assets/we_were_liars.jpg",
//     "tags": [
//         "Contemporary",
//         "Fiction"],
//   },
//   {
//     "id": 11,
//     "title": "How to Be Bad Kindle Edition",
//     "price": 19,
//     "author": "  Lauren Myracle ",
//     "subject":"Best friends, Jess and Vicks, aren't clicking like they use to, so Jess has a plan that will bring her and Vicks close again - a road trip to see Vicks's boyfriend, Brady, who is at University. There's only one issue, they don't have enough money to fund the trip. Enter Mel, the new girl. Mel volunteers to help them fund the trip as long as they take her along with them, much to Jess's dismay. ",
//     "publish_date": "21-04-2009",
//     "imageUrl": "assets/how_to_Be_Bad.jpg",
//     "tags": ["Contemporary"],
//   },
//   {
//     "id": 12,
//     "title": "If the Shoe Fits",
//     "price": 10,
//     "author": "  Sarah Mlynowski  ",
//     "subject":" A series puts a fresh spin on the Cinderella story!Tonight the mirror swept us into Cinderella's fairy tale. Now, we are NOT messing this story up. No way. Cinderella is going to marry her prince just like she's supposed to. Uh-oh. Cinderella broke her foot and there's massive swelling. The glass slipper won't fit, the prince won't know she's the one for him, and they won't live happily ever after.",
//     "publish_date": "01-01-2013",
//     "imageUrl": "assets/shoe_fits.jpg",
//     "tags": [ "Contemporary"],
//   },
//   {
//     "id": 13,
//     "title": "Where the Sky Begins",
//     "price": 12,
//     "author": "  Rhys Bowen ",
//     "subject":" A woman’s future is determined by fate and choice in a gripping WWII novel about danger, triumph, and second chances by the New York Times bestselling author of The Venice Sketchbook and The Tuscan Child. ",
//     "publish_date": "2-08-2022",
//     "imageUrl": "assets/where_the_sky_begins.jpg",
//     "tags": ["Fiction"],
//   },
//   {
//     "id": 14,
//     "title": "What Divides Us",
//     "price": 14,
//     "author": " Jean Grainger ",
//     "subject": " 29-07-2022 ",
//     "publish_date":"On the face of it, life is idyllic for Eli and Lena Kogan. Living in their beautiful house in the Irish countryside, their children are growing up happy and safe surrounded by a loving community. ",
//     "imageUrl": "assets/what_divides_us.jpg",
//     "tags": ["Fiction"],
//   },
//   {
//     "id": 15,
//     "title": "Light to the Hills",
//     "price": 15,
//     "author": " Bonnie Blaylock ",
//     "subject":" A beautiful story about life in the Appalachian hills in the 1930s. Men were in the coal mines, there was no education for girls, life was beyond poor. But for the MacInteer Family their faith and family pulled them through, and they persevered.",
//     "publish_date": "02-12-2022",
//     "imageUrl": "assets/light_to_hills.jpg",
//     "tags": ["Fiction"],
//   },
//   {
//     "id": 16,
//     "title": " 2 States ( The Story Of My Marriage)",
//     "price": 15,
//     "author": " Chetan Bhagat  ",
//     "subject": "Love marriages around the world are simple: Boy loves girl. Girl loves boy. They get married. In India, there are a few more steps: Boy loves Girl. Girl loves Boy. Girl's family has to love boy. Boy's family has to love girl. Girl's Family has to love Boy's Family. Boy's family has to love girl's family. Girl and Boy still love each other.",
//     "publish_date": "10-07-2021",
//     "imageUrl": "assets/2_states.jpg",
//     "tags": ["Contemporary"],
//   },
//   {
//     "id": 17,
//     "title": "  Halfgirlfriend  ",
//     "price": 8,
//     "author": " Chetan Bhagat",
//     "subject":" Half Girlfriend is an Indian English coming of age, young adult romance novel by Indian author Chetan Bhagat.[1] The novel, set in rural Bihar, New Delhi, Patna, and New York, is the story of a Bihari boy on a quest of winning over the girl he loves. ",
//     "publish_date": "13-08-2014",
//     "imageUrl": "assets/halfgirlfriend.jpg",
//     "tags": ["Contemporary"],
//   },
//   {
//     "id": 18,
//     "title": " The Old Curiosity Shop ",
//     "price": 19,
//     "author": " Charles Dickens ",
//     "subject":" With The Old Curiosity Shop we have exactly that experience - in abundance. Plus in the final chapter we have, as always, a satisfying explanation of what has happened to all the main characters. Even the cantankerous and self-willed horse 'Whiskers', whose antics more than once released the tension from a particularly harrowing part of the story, is given his own summing-up, his own 'happy ending' in the final chapter.  ",
//     "publish_date": "01-01-1840",
//     "imageUrl": "assets/the_old_curiosity_shop.jpg",
//     "tags": ["Fiction"],
//   },
//   {
//     "id": 19,
//     "title": "Open Secrets",
//     "price": 13,
//     "author": "Alice Munro ",
//     "subject": " Alice Munro’s Open Secrets is so liberating and exciting for any new story writer to feel her open textures, her bold reach, her plainness, with no showing off, no special effects. She reminds us that there’s no formula for a story, it can be as loosely woven as you like, as long as the inner logic works organically. Easier said of course, much easier said, than done. ",
//     "publish_date": "  01-12-2005  ",
//     "imageUrl": "assets/open.jpg",
//     "tags": [" Politics"],
//   },
//   {
//     "id": 20,
//     "title": "  Our Story Begins ",
//     "price": 16,
//     "author": " Tobias Wolff ",
//     "subject": " Tobias Wolff’s Our Story Begins is much more than a vast manual of examples of how to build great characters, unforgettable situations, and powerful dialogues. It shows how great stories are always born of small details and grow thanks to a power of invocation that is reinforced word by word, as a vital spell, which can only be built by walking hand in hand with the reader. ",
//     "publish_date": " 07-04-2009",
//     "imageUrl": "assets/our_story_begins.jpg",
//     "tags": ["Fiction"],
//   },
//   {
//     "id": 21,
//     "title": "A Good Man Is Hard to Find",
//     "price": 4,
//     "author": " Flannery O’Connor ",
//     "subject":" Every young writer should read Flannery O’Connor’s A Good Man Is Hard to Find at least three or four times. If you’ve ever thought creativity was opposed to clarity, or that funny stories aren’t serious, or that stories about abnormal people are about abnormal people, or that the road to the realistic was through realism—O’Connor is here to disabuse you, with pleasure.  ",
//     "publish_date": "08-09-2003",
//     "imageUrl": "assets/goodman_hard_to_find.jpg",
//     "tags": [" Fiction"],
//   },
//   {
//     "id": 22,
//     "title": "Airships",
//     "price": 9,
//     "author": " Barry Hannah ",
//     "subject":" Hannah’s work was an attack on hungry time itself—his words—and the campaign was successful.  His stories are alive.  I recommend them to readers and writers for the surprise and uplift of his prose. His sentences abound with syntactical twists, archaic words, bardlike phrases, Biblical notes.",
//     "publish_date": "01-01-2009",
//     "imageUrl": "assets/airships.jpg",
//     "tags": ["Literature"],
//   },
//   {
//     "id": 23,
//     "title": " Oliver Twist ",
//     "price": 18,
//     "author": " Charles Dickens ",
//     "subject":"Oliver Twist is born into a life of poverty and misfortune, raised in a workhouse in the fictional town of Mudfog. The children working there receive very little food; after six months, they draw lots, with the loser asking for another portion of gruel. Oliver is designated, and so he approaches workhouse manager Mr. Bumble and humbly requests another serving. ",
//     "publish_date": "09-02-1837",
//     "imageUrl": "assets/oliver_twist.jpg",
//     "tags": ["Literature"],
//   },
//   {
//     "id": 24,
//     "title": " Geronimo Rex",
//     "price": 18,
//     "author": " Barry Hannah ",
//     "subject":"Geronimo Rex, Barry Hannah's brilliant first novel, which was nominated for the National Book Award, is full of the rare verve and flawless turns of phrase that have defined his status as an American master. Roiling with love and torment, lunacy and desire, hilarity and tenderness, Geronimo Rex is the bildungsroman of an unlikely hero.",
//     "publish_date": "09-02-1837",
//     "imageUrl": "assets/geronimo_rex.jpg",
//     "tags": ["Fiction", "Literature"],
//   },

// ]